# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3896c44607805b8bbbdc7eb372626ab1027c62c70f5564f8971b86b3553af4968309580b81e3b39e28459ae9f74091d5a50f3718ebf19be4c01e0fb25b22332e

test:
  secret_key_base: 0a75d939bc3034cfc8ca5aa28e5698cab812d46ffea9c51909201e0a8c779312dbca04c0a3c8cbde902408c160c5c34e8428527f182d8a2ce9d1067e6669e245

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
